SUBSTREAMS ?= substreams
MODULE ?= map_transfers
START_BLOCK ?= 12292922
BLOCK_COUNT ?= 10

.PHONY: build check test fmt lint pack stream graph codegen
build:
	cargo build --locked --target wasm32-unknown-unknown --release

check: fmt lint test

fmt:
	cargo fmt -- --check

lint:
	cargo clippy --locked --all-targets -- -D warnings

test:
	cargo test --locked --lib

pack: build
	$(SUBSTREAMS) pack substreams.yaml

# Bounded live check; authenticate with `substreams auth` first.
stream: pack
	$(SUBSTREAMS) run substreams.yaml $(MODULE) -s $(START_BLOCK) -t +$(BLOCK_COUNT) -o jsonl

graph:
	$(SUBSTREAMS) graph substreams.yaml

# Both protobuf and ABI bindings are generated by build.rs into target/.
codegen:
	cargo check --locked
